ALTER TABLE crypto_news
ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE crypto_prices
ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE fear_greed_index
ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE crypto_prices SET fetched_at = CURRENT_TIMESTAMP WHERE fetched_at is NULL;
UPDATE crypto_news SET fetched_at = CURRENT_TIMESTAMP WHERE fetched_at is NULL;
UPDATE fear_greed_index SET fetched_at = CURRENT_TIMESTAMP WHERE fetched_at is NULL;


